stages:
  - build
  - deploy
  - cleanup

variables:
  REBUILD:
    value: "true"
    options:
      - "true"
      - "false"
    description: "Force rebuild of the container image."
  IMAGE_NAME: ms-ib-collector
  CACHED_COMMAND: "--no-cache"
  CONTAINER_VERSION: "v0.0.1"

MS_IB_COLLECTOR_BUILD:
  stage: build
  tags:
    - PG
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - |
      if [ "${REBUILD}" != "true" ]; then
        echo "REBUILD is ${REBUILD}, skipping build";
      else
        CONTAINER_TAG="${CI_COMMIT_SHORT_SHA}"

        echo "Building image with tag: ${CONTAINER_TAG}";

        docker build $CACHED_COMMAND \
          --network=host \
          --build-arg BUILD_REF=${CONTAINER_TAG} \
          -t "$CONTAINER_REGISTRY/$IMAGE_NAME:${CONTAINER_TAG}" \
          -t "$CONTAINER_REGISTRY/$IMAGE_NAME:latest" .;

        docker push "$CONTAINER_REGISTRY/$IMAGE_NAME:${CONTAINER_TAG}";
        docker push "$CONTAINER_REGISTRY/$IMAGE_NAME:latest";

        echo "Successfully pushed image: $CONTAINER_REGISTRY/$IMAGE_NAME:${CONTAINER_TAG}";
        echo "Successfully pushed image: $CONTAINER_REGISTRY/$IMAGE_NAME:latest";

        yes | docker image prune -a --filter "until=$(date +'%Y-%m-%dT%H:%M:%S' --date='-1 days')" || true;
      fi
